- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: install .bashrc
      blockinfile:
        path: ~/.bashrc
        block: "{{ lookup('file', '.bashrc') }}"

    - name: install .blerc
      blockinfile:
        path: ~/.blerc
        block: "{{ lookup('file', '.blerc') }}"
        create: true

    - name: install .vimrc
      blockinfile:
        path: ~/.vimrc
        block: "{{ lookup('file', '.vimrc') }}"
        create: true
        marker: '" {mark} ANSIBLE MANAGED BLOCK'

    - name: install .inputrc
      blockinfile:
        path: ~/.inputrc
        block: "{{ lookup('file', '.inputrc') }}"
        create: true

    - name: install .screenrc
      blockinfile:
        path: ~/.screenrc
        block: "{{ lookup('file', '.screenrc') }}"
        create: true

    - name: install .config/bat/config
      blockinfile:
        path: ~/.config/bat/config
        block: "{{ lookup('file', './.config/bat/config') }}"
        create: true
